project_id = "yasedaxyeogpnhiaqvpk"

[functions.notion-oauth-callback]
verify_jwt = false

[functions.save-to-notion]
verify_jwt = true

[functions.generate-summary]
verify_jwt = true

[functions.generate-oauth-state]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = true

[functions.analyze-behavior]
verify_jwt = true

[functions.analyze-drawing]
verify_jwt = true
